name: unit-tests
run-name: The workflow runs all the unit tests to make sure the code works correctly
on: [push, pull_request] # The same job will run twice as both the push and pull_request events go together
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      - run: npm install
      - run: npm run test